services:
  task-data:
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=titan
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - task-data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  task-data:
    driver: local